#语言 & Language
#English / Chinese(简体中文)
lang: Chinese
#储存方法 ： SQLite MYSQL
#Store method : SQLite MYSQL
Store: SQLite
Mysql:
  address: localhost
  port: 3306
  database: test
  user: root
  password: 123456
HikariCP:
  connectionTimeout: 30000
  #连接超时时间 默认值：30000（30秒）
  #Default connection timeout value: 30000 (30 seconds)
  minimumIdle: 10
  #最小空闲连接数
  #Minimum number of idle connections
  maximumPoolSize: 50
  #池允许达到的最大大小，包括空闲和正在使用的连接
  #The maximum allowed size of the pool, including idle and in use connections
settings:
  #该子服是否进行日期数据检测 （针对多子服，防止重复刷新）
  #进行日期检测以完成数据刷新，如果是多个子服建议只开启一个子服的该选项
  DataCheck: true
  #跨服模式 数据将会同步各个子服务器
  #Cross server mode data will be synchronized with each sub server
  Cross_Server:
    enable: false
    #该子服的名称（需与Bungeecord端的config下设定的一致）
    # The name of the sub server (must be consistent with the config.yml set in Bungerecord)
    server_name: 主服务器
  #创建公会相关设置
  #Create guild related settings
  create:
    #最长名字限制 （包含颜色字符）
    #Maximum name limit (including color characters)
    max-length: 6
    #退出、被踢出、解散公会后再次进入或创建一个公会的冷却时间。(分钟为单位)
    #The cooldown time for entering or creating a guild again after exiting, being kicked out, or disbanding the guild. (in minutes)
    cooldown: 240
    #默认组
    default:
      #有关于requirements配置请查看
      #Regarding the requirements configuration, please check
      #https://gyzerc.github.io/Gyzer.github.io/LegendaryGuild/Requirements.html
      requirements:
        - 'vault;5000'
        - 'playerpoints;100'
    groups:
      #ID 可随意取，不能重复
      #Can be taken freely and cannot be repeated
      普通会员组:
        #权重.越小先检测,不可重复
        #Weight. The smaller the value, the first to be detected and cannot be repeated
        weight: 3
        permission: 'legendaryguild.vip'
        requirements:
          - 'vault;4000'
          - 'playerpoints;80'
      高级会员组:
        weight: 2
        permission: 'legendaryguild.svip'
        requirements:
          - 'vault;3000'
          - 'playerpoints;50'
      超级会员组:
        weight: 1
        permission: 'legendaryguild.mvp'
        requirements:
          - 'vault;2000'
          - 'playerpoints;20'
  #Guild related settings
  guild:
    #每捐赠1游戏币获得多少点贡献
    #How many contributions do you earn for each donation of 1 game coin (Valut)
    moneyToPoints: 0.1
    #公会介绍最多行数
    introduce-max-line: 5
    #公会公告最多行数
    notice-max-line: 5
    level:
      #最高等级
      #the highest guild level
      max: 5
      #每级需要的经验
      #Experience required for each level
      require: [ 1000.0,5000.0,10000.0,50000.0,100000.0 ]
      #每级最大人数
      #Maximum number of people per level
      maxmembers: [ 5,10,15,20,25,50 ]
    #公会驻地设置 & Guild home settings
    home:
      #传送前等待多少秒
      #How many seconds to wait before transmission
      teleport_wait: 5
      #音效设置
      #sound settings
      sound:
        #传送前每秒发送的音效
        #Sound effects sent per second before teleport
        second: block_note_chime
        #传送取消时的音效
        #Sound effects when teleport cancellation
        cancel: entity_villager_no
        #传送音效
        #teleport sound
        teleport: entity_endermen_teleport
      #公会驻地设置不允许的世界名称
      #World names not allowed for guild residences
      black_world:
        - 'testWorld'
      #不允许的子服务器名称
      #Sub server name not allowed
      black_server:
        - '资源服'
    chat:
      # %player%
      #可使用 papi 变量
      #can use PlaceholderAPI
      format: '&f[&e公会聊天&f][%position%&f]&3%player%&f: %message%'