#是否启用该模块
enable: true
#公会神树相关
#Guild Tree related
#等级
#Level
level:
  #最大等级
  #the highest guild tree level
  max: 5
  #Experience required for each level
  requireExp: [ 1000.0,5000.0,10000.0,50000.0,100000.0 ]
  #进度条配置
  #Progress bar configuration
  bar:
    #长度
    length: 10
    #已达到进度字符
    #Progress Characters Reached
    completed: '&a■'
    #未达到进度字符
    #Progress character not reached
    empty: '&c■'
  #每级升级需要的花费
  #The cost required for each level of upgrade
  requirements:
    0:
      - 'guild_money;3000'
    1:
      - 'guild_money;5000'
    2:
      - 'guild_money;10000'
    3:
      - 'guild_money;15000'
    4:
      - 'guild_money;20000'
  #神树许愿设置
  #Guild Tree Wishing Setting
  wish:
    #0 级时候许愿执行
    #Make a wish to execute at level 0
    0:
      # %player% 为玩家名称
      #[player]指令 以玩家执行
      #[op]xx 以OP权限执行
      #[console]xx 从后台执行
      #[message]xx 向玩家发送消息
      #[title]xx;xx 向玩家发送标题
      #在最后面添加 ~chance:几率 代表有指定几率执行该行命令

      # %player% For player name
      #[player]xxx Executed by player
      #[op]xx Execute with OP permission
      #[console]xx Execute from the console
      #[message]xx Send messages to players
      #[title]xx;xx Send titles to players
      #Add '~chance:(0~1.0)' on the last side probability represents a specified chance to execute the command line
      run:
        - '[player]say 我完成了每日许愿'
        - '[console]money give %player% 50'
        #下面为 10%概率执行
        #The following is a 10% probability of execution
        - '[console]money give %player% 50 ~chance:0.1'
    1:
      run:
        - '[player]say 我完成了每日许愿'
        - '[console]money give %player% 150'
        - '[console]money give %player% 50 ~chance:0.1'
    2:
      run:
        - '[player]say 我完成了每日许愿'
        - '[console]money give %player% 250'
        - '[console]money give %player% 50 ~chance:0.1'
    3:
      run:
        - '[player]say 我完成了每日许愿'
        - '[console]money give %player% 350'
        - '[console]money give %player% 50 ~chance:0.1'
    4:
      run:
        - '[player]say 我完成了每日许愿'
        - '[console]money give %player% 450'
        - '[console]money give %player% 50 ~chance:0.1'
    5:
      run:
        - '[player]say 我完成了每日许愿'
        - '[console]money give %player% 550'
        - '[console]money give %player% 50 ~chance:0.1'
#神树各个等级的显示图标 &  Display icons for each level of the guild tree
tree:
  #等级 & level
  #config中设定了神树最大等级为多少，则这里就需要设置多少个 & If the maximum level of the divine tree is set in config, then how many need to be set here
  0:
    display: '&f&lGuild Tree &eLv.0'
    material: SAPLING
    data: 0
    model: 0
    lore:
      - ''
      - '&fLevel: &e%level%'
      - '&fExp: &e%exp%/%next% &7(%bar%&7)'
      - '&fUpgrade required:'
      - '&f - &7Guild Money×3000'
      - ''
      - '&eClick to upgrade'
  1:
    display: '&f&lGuild Tree &eLv.1'
    material: SAPLING
    data: 0
    model: 0
    lore:
      - ''
      - '&fLevel: &e%level%'
      - '&fExp: &e%exp%/%next% &7(%bar%&7)'
      - '&fUpgrade required:'
      - '&f - &7Guild Money×5000'
      - ''
      - '&eClick to upgrade'
  2:
    display: '&f&lGuild Tree &eLv.2'
    material: SAPLING
    data: 0
    model: 0
    lore:
      - ''
      - '&fLevel: &e%level%'
      - '&fExp: &e%exp%/%next% &7(%bar%&7)'
      - '&fUpgrade required:'
      - '&f - &7Guild Money×10000'
      - ''
      - '&eClick to upgrade'
  3:
    display: '&f&lGuild Tree &eLv.3'
    material: SAPLING
    data: 0
    model: 0
    lore:
      - ''
      - '&fLevel: &e%level%'
      - '&fExp: &e%exp%/%next% &7(%bar%&7)'
      - '&fUpgrade required:'
      - '&f - &7Guild Money×15000'
      - ''
      - '&eClick to upgrade'
  4:
    display: '&f&lGuild Tree &eLv.4'
    material: SAPLING
    data: 0
    model: 0
    lore:
      - ''
      - '&fLevel: &e%level%'
      - '&fExp: &e%exp%/%next% &7(%bar%&7)'
      - '&fUpgrade required:'
      - '&f - &7Guild Money×20000'
      - ''
      - '&eClick to upgrade'
  5:
    display: '&f&lGuild Tree &eLv.MAX'
    material: SAPLING
    data: 0
    model: 0
    lore:
      - ''
      - '&fLevel: &e%level%'
      - '&fExp: &e%exp%'
      - '&fCurrently at maximum level'
      - ''
      - '&eClick to upgrade'